name: "it"
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - uses: ./
      with:
        airtable-token: ${{ secrets.AIRTABLE_TOKEN }}
        airtable-base: ${{ secrets.AIRTABLE_BASE}}
        airtable-sheet: events
